### PR TITLE
docs: add demo video

### PR DESCRIPTION
**Pull request by aramase**
**Reason for Change**:

- Adds demo gif for the provider

**Requirements**

- [x] squashed commits
- [x] included documentation
- [x] added unit tests and e2e tests (if applicable).

**Issue Fixed**:

**Please answer the following questions with yes/no**:

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?

**Special Notes for Reviewers**:

### CODE REVIEW

**Comment by ritazh** [comment]
@aramase The demo looks great! The recording/gif font is really small. Is there any way to make it a little bigger?

**Review by ritazh — APPROVED** [review]
lgtm

**Comment by ritazh** [comment]
Would be nice to get the demo script too if it's not too much work to scrub it.

**Comment by aramase** [comment]
> Would be nice to get the demo script too if it's not too much work to scrub it.

For sure. Opened an issue for it - https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/293. I'll clean up the script and open a PR.

**Pull request merged**
