### PR TITLE
feat: migrate from `autorest/adal` to `azidentity`

### LINKED ISSUE #996: Migrate from `autorest/adal` to `azidentity`
ref: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/MIGRATION.md

### PR DESCRIPTION
**Pull request by aramase**
Signed-off-by: Anish Ramasekar <anish.ramasekar@gmail.com>

**Reason for Change**:

- Updates the auth code to use `azidentity` as adal is deprecated.
- In order to keep the scope small, the PR uses the adapter https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/MIGRATION.md#use-azidentity-credentials-with-older-packages to continue using the old sdk for keyvault. I'll update this in a follow-up PR.

**Requirements**

- [ ] squashed commits
- [ ] included documentation
- [ ] added unit tests and e2e tests (if applicable).

**Issue Fixed**:

fixes #996 

**Does this change contain code from or inspired by another project?**

- [ ] Yes
- [ ] No

**If "Yes," did you notify that project's maintainers and provide attribution?**

**Special Notes for Reviewers**:

### CODE REVIEW

**Review by aramase — COMMENTED** [review]
Windows tests are failing because the image we use for test pods is broken on windows

```
  Warning  FailedMount  26s                kubelet            MountVolume.SetUp failed for volume "secrets-store-inline" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod key-9zhtd/busybox-secrets-store-inline-crd, err: error connecting to provider "azure": provider not found: provider "azure"
  Normal   Pulling      5s                 kubelet            Pulling image "k8s.gcr.io/e2e-test-images/busybox:1.29"
  Warning  Failed       4s                 kubelet            Failed to pull image "k8s.gcr.io/e2e-test-images/busybox:1.29": rpc error: code = NotFound desc = failed to pull and unpack image "k8s.gcr.io/e2e-test-images/busybox:1.29": no match for platform in manifest: not found
```

i'll debug this in a bit and update the image to a working one in a different PR!

**Comment by aramase** [comment]
> Windows tests are failing because the image we use for test pods is broken on windows
> 
> ```
>   Warning  FailedMount  26s                kubelet            MountVolume.SetUp failed for volume "secrets-store-inline" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod key-9zhtd/busybox-secrets-store-inline-crd, err: error connecting to provider "azure": provider not found: provider "azure"
>   Normal   Pulling      5s                 kubelet            Pulling image "k8s.gcr.io/e2e-test-images/busybox:1.29"
>   Warning  Failed       4s                 kubelet            Failed to pull image "k8s.gcr.io/e2e-test-images/busybox:1.29": rpc error: code = NotFound desc = failed to pull and unpack image "k8s.gcr.io/e2e-test-images/busybox:1.29": no match for platform in manifest: not found
> ```
> 
> i'll debug this in a bit and update the image to a working one in a different PR!

https://github.com/Azure/secrets-store-csi-driver-provider-azure/pull/1079 should resolve this!

**Review by nilekhc — APPROVED** [review]

**Pull request merged**
