### PR TITLE
Allow the 'updateStrategy' of the Daemonset to be configured in Helm

### LINKED ISSUE #283: Support configuring updateStrategy.rollingUpdate.maxUnavailable in Helm charts
**Describe the solution you'd like**
Right now the Helm Charts configure Daemonsets with the RollingUpdate strategy, but don't provide any option so specify the 'maxUnavailble' property, so the default value of '1' is being used.  On our 60+ node clusters this is causing the deployment to take 40+ minutes to complete.  It would be great if the Helm charts allowed 'maxUnavailable' to be configurable so more than one node can be updated at once.

**Anything else you would like to add:**
This should apply to both Azure/secrets-store-csi-driver-provider-azure and kubernetes-sigs/secrets-store-csi-driver.  Should I open a second issue over there?

Related question, but what is the impact when a single node is being updated?  Would new pods using the Secrets Store CSI Driver be blocked from coming online until the update is complete on that node?

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Azure Key Vault provider version: (use the image tag):
- Kubernetes version: (use `kubectl version`):
- Cluster type: (e.g. AKS, aks-engine, etc):

### PR DESCRIPTION
**Pull request by chrisamert**
**Reason for Change**:

This PR enables the 'updateStrategy' of the Daemonset to be configured by Helm parameters.  The default values are the same as the current defaults; RollingUpdate strategy with maxUnavailable set to 1, so behavior will change only if the user specifies a custom value.

**Requirements**

- [x] squashed commits
- [x] included documentation
- [x] added unit tests and e2e tests (if applicable).

**Issue Fixed**:

Fixes #283 283
**Please answer the following questions with yes/no**:

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?  No

**Special Notes for Reviewers**:

### CODE REVIEW

**Review by aramase — CHANGES_REQUESTED** [review]
@chrisamert This changes to be made in the `manifest_staging` dir where we currently host the staging charts. Could you make the changes only in [manifest_staging/charts](https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master/manifest_staging/charts/csi-secrets-store-provider-azure) instead

**Comment by chrisamert** [comment]
Ahh I missed that. I'll get these changes moved over

**Comment by aramase** [comment]
Adding the default values from docs here for future reference-

```
RollingUpdate: This is the default update strategy.
With RollingUpdate update strategy, after you update a DaemonSet template, old DaemonSet pods will be killed, and new DaemonSet pods will be created automatically, in a controlled fashion. At most one pod of the DaemonSet will be running on each node during the whole update process.
```

```
You may want to set .spec.updateStrategy.rollingUpdate.maxUnavailable (default to 1) and .spec.minReadySeconds (default to 0) as well.
```

Ref docs:
https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/#daemonset-update-strategy
https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/#performing-a-rolling-update

**Review by aramase — APPROVED** [review]
lgtm

**Pull request merged**
