### PR TITLE
Comment out chart resources values

### PR DESCRIPTION
**Pull request by matrus2**
**Reason for Change**:
In the provided chart you specified exact resources (CPU, memory) values for csi secret store DaemonSet object. We would like to have a full control of these values and not set CPU limits at all per [article](https://home.robusta.dev/blog/stop-using-cpu-limits). Currently, it is impossible see helm issue [here](https://github.com/helm/helm/issues/9027). In short:

You set in values.yaml:
```
  resources:
    limits:
      cpu: 100m
```
I would like to set in my parent chart the following value for your resources:
```
  resources:
    limits:
      cpu: null
```
But `helm template` command will result in:
```
  resources:
    limits:
      cpu: 100m
```

There is no way I can disable setting cpu limits.

Notes:
I left your values commented out as a recommendation of resources configuration.

### CODE REVIEW

**Comment by matrus2** [comment]
@microsoft-github-policy-service agree [company="default"]

**Review by aramase — COMMENTED** [review]
> In the provided chart you specified exact resources (CPU, memory) values for csi secret store DaemonSet object. We would like to have a full control of these values and not set CPU limits at all per [article](https://home.robusta.dev/blog/stop-using-cpu-limits). Currently, it is impossible see helm issue https://github.com/helm/helm/issues/9027.

The default values in the charts are set based on load testing the driver and provider. The best practice is for the project to set the resource requests and limits in the chart based on testing and also making it configurable for users in the helm charts. If you do not need the cpu limit, you can comment it out in your values file and it won't show up in the deployment. It is possible through helm and the values file is for configuration. I just commented it out and test `helm template`, I can confirm cpu limit is not set. 

```yaml
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      # cpu: 50m
      memory: 100Mi
```

rendered yaml from helm template
```yaml
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 100Mi
```

if you're referring to the resource limits in the `secrets-store-csi-driver` sub chart, you can configure those values using `secrets-store-csi-driver` prefix in the values (ex: `secrets-store-csi-driver.linux.driver.resources`). The list of customizable values are here: https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/main/charts/secrets-store-csi-driver#configuration. If these are the resources you're referring to in the PR description, then the change is incorrect.

**Comment by aramase** [comment]
We want to set the default resource limits in the manifests and charts we provide OOTB. It's configurable using helm, so I'm going to close out this PR! Thanks.

**Comment by matrus2** [comment]
@aramase  I would like first of all to thanks that you share the results of your load testing and include this as values for resources configuration. Although, the way how you do it doesn't make them configurable as I'm unable to unset CPU limits. I can't comment them out as I'm using your chart as a subchart and later I use helm controller to pull it to the cluster. This way:

```
#chart.yaml
apiVersion: v2
name: My chart
description: A Helm chart for Kubernetes
type: application
version: 0.15.7-5
dependencies:
  - name: csi-secrets-store-provider-azure
    alias: csi
    version: 1.3.0
    repository: "@csi-secrets-store-provider-azure"
    condition: csi.enabled
```

And if I set in my values.yaml:
```
csi:
  enabled: true
  secrets-store-csi-driver:
    linux:
      driver:
        resources:
          limits:
            cpu: null
            memory: 70Mi
          requests:
            cpu: 10m
            memory: 70Mi
...
```

The result would be:
```
          resources:
            limits:
              cpu: 200m
              memory: 70Mi
            requests:
              cpu: 10m
              memory: 70Mi
```

There is no way to unset it. The reason for this I already mentioned is Helm issue that once something is set can not be removed - see https://github.com/helm/helm/issues/9027. 

Your chart looks well written as you are using `{{ toYaml .Values.linux.resources | indent 12 }}`, which means template is fully configurable. However, if you set values in values.yaml the flexibility is gone. It is a good practice I observe in all other chart that recommended values are commented out - see for example bitnami charts.

Please reconsider how you provide your recommendation for configuration.

**Pull request closed without merging**
