### PR TITLE
feat: adds windows server 2022

### PR DESCRIPTION
**Pull request by nick5616**
**Reason for Change**:

Adds _Windows Server 2022_ to `Makefile`, `BASEIMAGE`, and `BASEIMAGE_CORE`

**Requirements**

- [x] squashed commits
- [ ] included documentation
- [ ] added unit tests and e2e tests (if applicable).

**Issue Fixed**:

**Does this change contain code from or inspired by another project?**

- [ ] Yes
- [x] No

**If "Yes," did you notify that project's maintainers and provide attribution?**

**Special Notes for Reviewers**:
ltsc2022 is the MCR tag for Windows Server 2022
https://hub.docker.com/_/microsoft-windows-nanoserver
There is a PR for the same thing here: 
https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1030
https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/756

### CODE REVIEW

**Comment by nilekhc** [comment]
@nick5616 Thanks for the PR!

Could you re-base?

**Review by nilekhc — APPROVED** [review]
lgtm

**Review by aramase — COMMENTED** [review]
/lgtm

**Pull request merged**
