### PR TITLE
Add priorityClassName to daemonsets.

### PR DESCRIPTION
**Pull request by derek-burdick**
**Reason for Change**:

This PR adds provides the option to add a priorityClassName to the PODS. In some environments, pods with a higher priority set can preempt this pod and cause issues with the driver. This also allows the scheduler to preempt lower priority pods if this pod needs to be recreated.

**Requirements**

- [x] squashed commits
- [ ] included documentation
- [ ] added unit tests and e2e tests (if applicable).

**Issue Fixed**:

**Please answer the following questions with yes/no**:

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?

**Special Notes for Reviewers**:

### CODE REVIEW

**Comment by derek-burdick** [comment]
FYI - I also submitted to secrets-store-csi-driver https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/337

**Review by aramase — COMMENTED** [review]
@derek-burdick Thank you for the PR!

Could you make these changes only in [manifest_changing/charts](https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master/manifest_staging/charts/csi-secrets-store-provider-azure) dir instead of charts dir? The chart changes are stored in the staging dir and move to charts during the release.

**Comment by derek-burdick** [comment]
@aramase  Thanks for quick response. I moved the change and rebased off of latest.

**Review by aramase — APPROVED** [review]
lgtm

**Review by ritazh — APPROVED** [review]
lgtm

**Pull request merged**
