### PR TITLE
chore: remove old helm packages and index

### PR DESCRIPTION
**Pull request by aramase**
Signed-off-by: Anish Ramasekar <anish.ramasekar@gmail.com>

**Reason for Change**:

- Removes old helm packages and index
  - The helm chart packages have been moved to `gh-pages`. 

> Note: The helm chart repository URL has changed from `https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts` to `https://azure.github.io/secrets-store-csi-driver-provider-azure/charts`.

**Requirements**

- [ ] squashed commits
- [ ] included documentation
- [ ] added unit tests and e2e tests (if applicable).

**Issue Fixed**:

**Does this change contain code from or inspired by another project?**

- [ ] Yes
- [ ] No

**If "Yes," did you notify that project's maintainers and provide attribution?**

**Special Notes for Reviewers**:

### CODE REVIEW

**Review by nilekhc — APPROVED** [review]

**Review by nilekhc — APPROVED** [review]

**Comment by zhangxin511** [comment]
This change breaks the existing customer behavior... Can't we use 302 to redirect instead of 404 for the request?

**Comment by aramase** [comment]
> This change breaks the existing customer behavior... Can't we use 302 to redirect instead of 404 for the request?
Sample of our logs:

@zhangxin511 We stopped publishing helm charts to master branch about 6 months back. None of the support release helm charts are available here. This was added in the previous release note and now we're finally removing it. Could you try updating to the latest helm chart url?

**Pull request merged**
