### PR TITLE
docs: Added doc website

### LINKED ISSUE #256: Create a documentation site for Azure Key Vault Provider
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Azure Key Vault provider version: (use the image tag):
- Kubernetes version: (use `kubectl version`):
- Cluster type: (e.g. AKS, aks-engine, etc):

### PR DESCRIPTION
**Pull request by phillipgibson**
**Reason for Change**:

Added documentation static website

**Requirements**

- [ ] squashed commits
- [X] included documentation
- [ ] added unit tests and e2e tests (if applicable).

**Issue Fixed**:

fixes #256 

**Please answer the following questions with yes/no**:

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?

**Special Notes for Reviewers**:

### CODE REVIEW

**Comment by phillipgibson** [comment]
We will integrate Netlify preview capabilities after merge.

**Review by aramase — CHANGES_REQUESTED** [review]
@phillipgibson We don't need to add the vendor dir in `themes/docsy/assets`. I believe it's just added as a submodule?

**Comment by phillipgibson** [comment]
I have it in the .gitmodules file. Do I need to initialize the submodule path and do another PR?

**Comment by aramase** [comment]
> I have it in the .gitmodules file. Do I need to initialize the submodule path and do another PR?

The `website/themes/docsy` needs to be in .gitmodule. I see in this PR the vendor dir is in the `.gitmodules`. Ref: https://github.com/Azure/aad-pod-identity/blob/master/.gitmodules

**Comment by aramase** [comment]
@phillipgibson Let me know if you want to pair on this.

**Comment by phillipgibson** [comment]
I think I'm going to pull this PR back and make some changes on the site first and then re-submit.

**Pull request closed without merging**
