### PR TITLE
Added kubeletRootDir variable

### LINKED ISSUE #521: Secret failed to write to file on Microk8s
**Have you**

- [X] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [X] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
We follow your tutorial: https://azure.github.io/secrets-store-csi-driver-provider-azure/demos/standard-walkthrough/
down through connecting our existing keyvault and service principal. We created a kubernetes secret and followed using the example secretproviderclass given with busybox. When the pod tries to start, it fails to write the secret to file.

Describe Pod
```
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    9m7s                 default-scheduler  Successfully assigned default/busybox-secrets-store-inline to nathan-xps
  Warning  FailedMount  43s (x12 over 9m7s)  kubelet            MountVolume.SetUp failed for volume "secrets-store-inline" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Unknown desc = failed to mount secrets store objects for pod default/busybox-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to write file BackendDatabaseUserPassword at /var/snap/microk8s/common/var/lib/kubelet/pods/4e141856-aefb-4a29-8f87-14daa3e9667a/volumes/kubernetes.io~csi/secrets-store-inline/mount: open /var/snap/microk8s/common/var/lib/kubelet/pods/4e141856-aefb-4a29-8f87-14daa3e9667a/volumes/kubernetes.io~csi/secrets-store-inline/mount/BackendDatabaseUserPassword: no such file or directory
  Warning  FailedMount  16s (x4 over 7m5s)   kubelet            Unable to attach or mount volumes: unmounted volumes=[secrets-store-inline], unattached volumes=[secrets-store-inline default-token-w2h45]: timed out waiting for the condition

```
Logs:
`E0528 19:20:50.702213       1 grpc.go:29] "GRPC error" err="failed to mount objects, error: failed to write file BackendDatabaseUserPassword at /var/snap/microk8s/common/var/lib/kubelet/pods/4e141856-aefb-4a29-8f87-14daa3e9667a/volumes/kubernetes.io~csi/secrets-store-inline/mount: open /var/snap/microk8s/common/var/lib/kubelet/pods/4e141856-aefb-4a29-8f87-14daa3e9667a/volumes/kubernetes.io~csi/secrets-store-inline/mount/BackendDatabaseUserPassword: no such file or directory"`

test.yaml we were using:
```
kind: Pod
apiVersion: v1
metadata:
  name: busybox-secrets-store-inline
spec:
  containers:
  - name: busybox
    image: k8s.gcr.io/e2e-test-images/busybox:1.29
    command:
      - "/bin/sleep"
      - "10000"
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-kvname"
        nodePublishSecretRef:                       # Only required when using service principal mode
          name: secrets-store-creds   
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: "kvname"
    objects: |
      array:
        - | #Backend ----------------------------------------------------------
          objectName: BackendDatabaseUserPassword
          objectType: secret
          objectVersion: "" 
    tenantId: "1234
```

**What did you expect to happen:**
It to work and start.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Started from scratch, so should be working with your examples.

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]
Service Principal

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): latest
- Azure Key Vault provider version: (use the image tag): latest
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): 1.17.17
- Cluster type: (e.g. AKS, aks-engine, etc): Microk8s

### PR DESCRIPTION
**Pull request by dmcconnell-m**
**Reason for Change**:

**Requirements**

- [ ] squashed commits
- [ ] included documentation
- [ ] added unit tests and e2e tests (if applicable).

**Issue Fixed**:
Fixes #521 

**Does this change contain code from or inspired by another project?**

- [ ] Yes
- [X] No

**If "Yes," did you notify that project's maintainers and provide attribution?**

**Special Notes for Reviewers**:

### CODE REVIEW

**Comment by nilekhc** [comment]
> [CLA assistant check](https://cla.opensource.microsoft.com/Azure/secrets-store-csi-driver-provider-azure?pullRequest=539)
> Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/Azure/secrets-store-csi-driver-provider-azure?pullRequest=539) before we can accept your contribution.
> 
> ❌ dmcconnell-m [sign now](https://cla.opensource.microsoft.com/Azure/secrets-store-csi-driver-provider-azure?pullRequest=539)
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/Azure/secrets-store-csi-driver-provider-azure?pullRequest=539) it.

@dmcconnell-m Thanks for opening the PR. Could you sign the `CLA`?

**Review by aramase — COMMENTED** [review]
@dmcconnell-m Thank you for the PR! Could you rebase it when you get a chance?

**Comment by dmcconnell-m** [comment]
@aramase done

**Review by nilekhc — APPROVED** [review]
lgtm

**Review by aramase — APPROVED** [review]

**Pull request merged**
