### PR TITLE
feat: allow empty objects array 

### PR DESCRIPTION
**Pull request by onlined**
**Reason for Change**:
The YAML for secret provider class can be created by a template engine and all the objects listed there can depend on a template variable to be truthy. In this case, when all of them are falsy, it becomes a special case if empty objects array is not allowed. Example:

```
objects: |
  array:
{{ if condition1 }}
   - |
     objectName: "Secret1"
     objectType: secret
     objectFormat: pfx
     objectEncoding: base64
{{ end }}
{{ if condition2 }}
   - |
     objectName: "Secret2"
     objectType: secret
     objectFormat: pfx
     objectEncoding: base64
{{ end }}
```

If `condition1` and `condition2` are both falsy, the provider returns an error, but simply mounting an empty volume would be more consistent and it doesn't require special handling.

**Requirements**

- [x] squashed commits
- [ ] included documentation
- [ ] added unit tests and e2e tests (if applicable).

**Issue Fixed**:

**Does this change contain code from or inspired by another project?**

- [ ] Yes
- [x] No

**Special Notes for Reviewers**:

### CODE REVIEW

**Comment by onlined** [comment]
@aramase Can you review this? It's OK if we don't merge for some time.

**Comment by onlined** [comment]
@aramase ?

**Review by nilekhc — APPROVED** [review]
lgtm

**Review by aramase — APPROVED** [review]
/azp run pr-e2e

lgtm

**Pull request merged**
