### PR TITLE
ci: remove aks-engine cluster in test matrix

### LINKED ISSUE #754: Remove `aks-engine` tests and template from PR and nightly runs
- We have tests running with:
  - kind
  - aks-engine
  - AKS

clusters as part of our PR gate and nightly runs. As `aks-engine` will eventually be replaced with CAPZ, we should remove the aks-engine tests and templates.

### PR DESCRIPTION
**Pull request by aramase**
Signed-off-by: Anish Ramasekar <anish.ramasekar@gmail.com>

**Reason for Change**:

- Remove `aks-engine` clusters in test matrix
- Remove `aks-engine` cluster config
- Update to `v1.23.3` for kind tests

**Requirements**

- [x] squashed commits
- [ ] included documentation
- [ ] added unit tests and e2e tests (if applicable).

**Issue Fixed**:

fixes #754 

**Does this change contain code from or inspired by another project?**

- [ ] Yes
- [ ] No

**If "Yes," did you notify that project's maintainers and provide attribution?**

**Special Notes for Reviewers**:

### CODE REVIEW

**Comment by nilekhc** [comment]
Could we also run tests with nightly pipeline to make sure they work?

**Comment by aramase** [comment]
Nightly test results:
- https://dev.azure.com/AzureContainerUpstream/Secrets%20Store%20CSI%20Driver%20Provider%20Azure/_build/results?buildId=36399&view=results
- arc tests with `GINKGO_SKIP=should.mount.secret.file.with.given.permission`: https://dev.azure.com/AzureContainerUpstream/Secrets%20Store%20CSI%20Driver%20Provider%20Azure/_build/results?buildId=36437&view=results

**Pull request merged**
