### PR TITLE
Devcontainer and Local Debugging 

### LINKED ISSUE #25: Add Visual Studio Code Remote Containers support to Azure Provider
Configure the Azure Provider Repo to allow remote development through VS Code's Remote Containers extension. 

This will allow VS Code to be used as a full-featured development environment for the Azure Provider to ease development and debugging for contributors.

### PR DESCRIPTION
**Pull request by bdlb77**
**Reason for Change**:

Addition of Devcontainer and ability to debug changes made to the provider code

**Requirements**

- [ ] squashed commits
- [X] included documentation
- [ ] added unit tests and e2e tests (if applicable).

**Issue Fixed**:
Fixes #25 

**Please answer the following questions with yes/no**:

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?
no

**Special Notes for Reviewers**:

Attempting to split PR #45 

This PR will contain the the devcontainer, steps to setting up keyvault, and the steps needed to debug the provider within a remote devcontainer.

The Second half will be to enable running e2e-tests within the devcontainer and locally

### CODE REVIEW

**Comment by bdlb77** [comment]
@aramase  Here is the PR for the devcontainer and debugging within the devcontainer.. The small pieces for updating the bats tests I left out in the PR and will open up another PR. If you think that this is still too big, then I imagine I can split this to be purely the `devcontainer`, and I can create another PR that will include debugging within the devcontainer along with updating the bats tests

**Review by aramase — COMMENTED** [review]
@bdlb77 So, with the gRPC server changes we no longer support these flags in the binary - https://github.com/Azure/secrets-store-csi-driver-provider-azure/pull/251/files#diff-41ed8e6815f1720dc1cea91fbf10b4aeR71-R74. Could we do similar debug framework for gRPC?

**Comment by bdlb77** [comment]
Ah very good point I didn't think of with gRPC. I can rework it for the gRPC

**Comment by bdlb77** [comment]
closing this PR due to #272

**Pull request closed without merging**
