### PR TITLE
fix: update fluentd env var with new env var name

### PR DESCRIPTION
**Pull request by agreaves-ms**
**Reason for Change**:

This change fixes an issue with `genevafluentd_td_agent:mariner_20230915.3`:

image

This image appears to use an updated version of `fluentd` where the `FLUENTD_CONF` is no longer supported. Instead, the environment variable is now [`FLUENT_CONF`](https://docs.fluentd.org/configuration/config-file#fluent_conf-environment-variable).

With this change, fluentd is able to find the `fluentd.conf` file:

image

**Requirements**

- [ ] squashed commits
- [ ] included documentation
- [ ] added unit tests and e2e tests (if applicable).

**Issue Fixed**:

**Does this change contain code from or inspired by another project?**

- [ ] Yes
- [x] No

**If "Yes," did you notify that project's maintainers and provide attribution?**

**Special Notes for Reviewers**:

### CODE REVIEW

**Review by nilekhc — APPROVED** [review]

**Review by aramase — APPROVED** [review]

**Comment by nilekhc** [comment]
Force merging it since automated extension test pipeline needs to be fixed after migrating ext schema to v2.

**Comment by aramase** [comment]
> Force merging it since automated extension test pipeline needs to be fixed after migrating ext schema to v2.

@nilekhc should we open an issue to track this?

**Comment by nilekhc** [comment]
> > Force merging it since automated extension test pipeline needs to be fixed after migrating ext schema to v2.
> 
> @nilekhc should we open an issue to track this?

added https://github.com/Azure/secrets-store-csi-driver-provider-azure/pull/1380#issuecomment-1831043625

**Pull request merged**
