### PR TITLE
chore: updates amacoreagent for Arc

### PR DESCRIPTION
**Pull request by nilekhc**
**Reason for Change**:

This PR updates logging agent for Azure Arc.

**Requirements**

- [x] squashed commits
- [ ] included documentation
- [ ] added unit tests and e2e tests (if applicable).

**Issue Fixed**:

fixes https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/1363

**Does this change contain code from or inspired by another project?**

- [ ] Yes
- [x] No

**If "Yes," did you notify that project's maintainers and provide attribution?**

**Special Notes for Reviewers**:

### CODE REVIEW

**Comment by nilekhc** [comment]
> /hold until manual testing of extension.

@aramase This is ready for the review.

Passing CI -
https://dev.azure.com/AzureContainerUpstream/Secrets%20Store%20CSI%20Driver%20Provider%20Azure/_build/results?buildId=140152&view=logs&j=03075a16-d36a-54e7-7c05-b9c19971acd8

**Review by aramase — APPROVED** [review]

**Pull request merged**
